### ISSUE TITLE
Incorrect Usage error when running the example

### ISSUE THREAD

**Issue by greyarch** [janeczku/docker-machine-vultr#1]
I am trying to create a create a machine using docker-machine 0.4.1 on OSX 10.10.5, but I get an

Incorrect Usage 

message

the driver is on my path and is executable.
I am using the custom os (rancher) example command exactly as is, just substituting my API key.

Does this require docker-machine 0.5 perhaps?

**Comment by janeczku** [comment]
@greyarch thanks for reporting - 0.5 is required indeed!
