### ISSUE TITLE
Cannot run with Rancher Server

### ISSUE THREAD

**Issue by jmatsushita** [janeczku/docker-machine-vultr#10]
See rancher/rancher#4433

**Comment by jmatsushita** [comment]
Renaming the downloaded executable from `/usr/local/bin/docker-machine-driver-Vultr` to `/usr/local/bin/docker-machine-driver-vultr` did the trick.

**Comment by janeczku** [comment]
@jmatsushita Can't reproduce any file naming problems with the release. The distributed binary is named `docker-machine-driver-vultr` (all lowercase). How did you get the uppercase letter in yours?

**Comment by jmatsushita** [comment]
Hey @janeczku I've pasted the Github release tarball link into the Rancher Server driver install. So maybe it's some weird untaring side effect from Rancher Server...  #4433

**Comment by janeczku** [comment]
I just tried with Rancher Server v1.0.1 and the driver gets registered successfully. In any case this is probably an issue with Rancher rather than the driver. Thanks for pointing it out to me though!
