### ISSUE TITLE
Is RancherOS available on Vultr? 

### ISSUE THREAD

**Issue by jmatsushita** [janeczku/docker-machine-vultr#11]
It doesn't seem to show up on the os list https://api.vultr.com/v1/os/list

**Comment by janeczku** [comment]
You are right, it's not available as an OS option on Vultr. RancherOS is therefore installed via iPXE: https://www.vultr.com/docs/ipxe-boot-feature

**Comment by jmatsushita** [comment]
Right I see. The default OSID is 159 which is custom and allows IPXE and [this section](https://github.com/janeczku/docker-machine-vultr/blob/master/vultr.go#L194-L210) activates IPXE while [this one](https://github.com/janeczku/docker-machine-vultr/blob/master/vultr.go#L469-L484) creates the bootscript  from the latest RancherOS image. Got it.
