### ISSUE TITLE
can't get rancheros to ipxe boot

### ISSUE THREAD

**Issue by docteurklein** [janeczku/docker-machine-vultr#13]
It used to work seamlessly last time I tried, but right now I get an ipxe permission error;
It might come from the vultr API, so I tried allowing any IP to access to API, without success.

Here is a dump of the boot console it it can help:

![shot](https://cloud.githubusercontent.com/assets/109846/18607483/fac05d00-7ccd-11e6-86e8-d017557cfc95.png)

Any idea?
Thanks for any help :)

**Comment by robtagg** [comment]
I've also just started having the same issue and it looks like Vultr has disabled iPXE whilst they work on it. I can't find any timelines on this so really not sure how long it's going to be down for.
<img width="400" alt="screen shot 2016-09-28 at 23 27 05" src="https://cloud.githubusercontent.com/assets/3649093/18934716/3496828a-85d3-11e6-9348-444c4d8d6b00.png">

**Comment by docteurklein** [comment]
I opened a ticket there, and they said:

```

**Comment by docteurklein** [comment]
I also tried to contact the ipxe developers on IRC, and some users report having the same problem. didn't hear about any solution yet

**Comment by janeczku** [comment]
This is very annoying indeed 😬 . I asked them about the ETA for fixing their iPXE boot chain but didn't hear back from them yet...

**Comment by janeczku** [comment]
Response from Vultr

> This is unfortunately due to an issue with iPXE itself. The iPXE system uses it's own certification verification system, which is controlled by one of it's developers, and it seems that this system is having some difficulty at present. At this point, we've temporarily disabled iPXE installs and would suggest you seek other methods of installing your operating system of choice in the meantime. We appreciate your patience and understanding regarding this matter.
We've reported this to the iPXE developers, but unfortunately, we do not yet have an ETA as to when it will be resolved.

**Comment by docteurklein** [comment]
how original and personnalized answer :)

**Comment by janeczku** [comment]
🎉  iPXE booting is working again.

But: There is an issue in the initrd package of RancherOS v0.6.x that causes a kernel panic. You need to update the driver to [v1.1.0](https://github.com/janeczku/docker-machine-vultr/releases/tag/v1.1.0) which defaults to RancherOS v0.5.0 but also has a new flag to select a particular version to use.

**Comment by docteurklein** [comment]
@janeczku so cool! thanks for this!
