### ISSUE TITLE
Creating a new machine hangs with rpc warning

### ISSUE THREAD

**Issue by greyarch** [janeczku/docker-machine-vultr#2]
I am trying this with docker-machine 0.5.0-rc4 on OSX 10.10.5 and when I try to create a rancherOS machine all I get is a:

WARNING >>> Error attempting heartbeat call to plugin server: rpc: can't find method RpcServerDriver.Heartbeat

... and the process never finishes. The machine is not created.

**Comment by janeczku** [comment]
This should be fixed. The latest docker-machine release candidatae introduced some changes to the plugin API so i had to rebuilt the driver against the RC4.
