### ISSUE TITLE
Invoking vultr boot scripts

### ISSUE THREAD

**Issue by dmitrym0** [janeczku/docker-machine-vultr#21]
Is there a parameter for vultr-boot scripts? I can't seem to find it. All I'm trying to do is automatically add swap.

Thanks!

**Comment by dmitrym0** [comment]
FYI, vultr removed cloud-init support from Ubuntu images: https://discuss.vultr.com/discussion/998/why-is-cloud-init-no-longer-enabled-on-ubuntu-images

The linked thread describes how to work around it, but seems ugly. Support for their "native" scripts would be great.

**Comment by janeczku** [comment]
@dmitrym0 Thanks for the info. Support for startup boot scripts landed: https://github.com/janeczku/docker-machine-vultr/releases/tag/v1.2.2
Let me know if that works for you.

**Comment by dmitrym0** [comment]
Thanks @janeczku !
