### ISSUE TITLE
docker-machine create not compatible with VULTR firewall

### ISSUE THREAD

**Issue by Ecno92** [janeczku/docker-machine-vultr#24]
Hi, 

I just set up a machine using this Driver.

```
docker-machine create \
	--driver vultr \
	--vultr-api-key=$VULTR_API_KEY \
	--vultr-region-id=7 \
	--vultr-plan-id=201 \
	--vultr-backups=0 \
	--vultr-os-id=159 \
	--vultr-ros-version="v0.9.1" \
	pet-machine3
```

It boots up without any issues. 
After that I applied a new firewall configuration through the VULTR web interface.
With the following open ports:

TCP 22
TCP 80
TCP 443
TCP 2376
UDP 2376 as well...

Even with using the default ssh client of my Ubuntu desktop I can not connect when the firewall is enabled. 

I've also tried the Ubuntu image (215). It reproduces also with that configuration. 

When I boot a machine using a default system image from VULTR (e.g. Ubuntu) I can not reproduce the issue. 

I've reported the issue to VULTR, but I did not receive any update yet which allowed me to fix the configuration. I will make them aware of this issue report by referring it from the ticket. 

**Update:**

VULTR support was able to get it working on one specific machine. Other machines are still not working. I'm awaiting their feedback to see how we can get this fixed. 

**update 29-3-2017:**
Issue should be resolved, but I still need to verify this.

**Comment by janeczku** [comment]
@Ecno92 This seems to have been fixed on Vultr's side. Thanks!
