### ISSUE TITLE
Debian based distros no longer finish provisioning

### ISSUE THREAD

**Issue by samgurtman** [janeczku/docker-machine-vultr#27]
I've tested this with Debian 8, 9 and Ubuntu 17.04. None of them will complete provisioning. They each get to:

Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

**Comment by janeczku** [comment]
@samgurtman that's due to a bug in docker machine which was fixed in v0.12.1: https://github.com/docker/machine/issues/4156
