### ISSUE TITLE
The iPXE boot script is not removed on docker-machine rm

### ISSUE THREAD

**Issue by greyarch** [janeczku/docker-machine-vultr#4]
The iPXE boot script that is created for provisioning a rancherOS machine is not removed on machine removal.

**Comment by greyarch** [comment]
I am looking at your implementation of this, but (and correct me if I am wrong) it seems like the script will get removed even if it was not created by the plugin. I have the following scenarios in mind:
 - If I provide a boot script ID the plugin uses it to create a machine, but should not remove it on docker-machine rm...
 - Alternatively, if a boot script ID is not provided, the plugin should create a default boot script and remove it when the machine is created.

**Comment by janeczku** [comment]
Thats a good observation. I probably have to store custom boot script IDs in an extra field.
