### ISSUE TITLE
Add to docker/machine list of driver plugins

### ISSUE THREAD

**Issue by hairyhenderson** [janeczku/docker-machine-vultr#5]
There's now a list of available driver plugins in the Docker Machine docs: https://github.com/docker/machine/blob/master/docs/AVAILABLE_DRIVER_PLUGINS.md

It'd be great if the Vultr driver were listed there! :)

**Comment by janeczku** [comment]
@hairyhenderson Thank you for that info - i was in fact waiting for that to become available! :smiley:

**Comment by janeczku** [comment]
https://github.com/docker/machine/pull/2382

**Comment by hairyhenderson** [comment]
:tada: :confetti_ball: :grin:
