### ISSUE TITLE
mac binary 1.0.0 is not working

### ISSUE THREAD

**Issue by bradex** [janeczku/docker-machine-vultr#6]
I downloaded a mac binary from [release 1.0.0 page](https://github.com/janeczku/docker-machine-vultr/releases/tag/v1.0.0) , and I followed instructions but it didn't work with this error. (docker-machine version 0.5.6 build 61388e9, El Capitan 10.11.3)

```
docker-machine create --driver vultr --vultr-api-key=IEnteredRealAPIKey docker-test
Running pre-create checks...
(docker2) Validating Vultr VPS parameters...
(docker2) getting client
Error creating machine: Error with pre-create check: unexpected EOF
```

So, I built binary with go 1.5.3 and that works for me.

```
go get -u github.com/janeczku/docker-machine-vultr/bin
mv $GOPATH/bin/bin $GOPATH/bin/docker-machine-driver-vultr
```

I hope this will help.

**Comment by janeczku** [comment]
@bradex Possibly this: https://github.com/docker/machine/issues/2706

**Comment by janeczku** [comment]
Thanks for the report! Should be fixed in https://github.com/janeczku/docker-machine-vultr/commit/35ba3827c96c847755ccb839a9b47f5fbdd58839. New release v1.0.1 is up!
