### ISSUE TITLE
default os-id does not work

### ISSUE THREAD

**Issue by mtrofimm** [janeczku/docker-machine-vultr#8]
it seems there is a problem with downloading vmlinuz
![image](https://cloud.githubusercontent.com/assets/10633617/12841613/3bc76b1e-cbed-11e5-9561-901f022d41e7.png)

**Comment by mtrofimm** [comment]
I change the url for vmlinuz to http and looks OK.

**Comment by janeczku** [comment]
Yeah, looks like Vultr upgraded their iPXE boot image. Thanks for letting me know :+1:

**Comment by janeczku** [comment]
Fixed in https://github.com/janeczku/docker-machine-vultr/commit/6d4ae42e8ed56bda6f41e22f7693e9bc670c675a
