### ISSUE TITLE
the rancheros instance does not mount storage

### ISSUE THREAD

**Issue by docteurklein** [janeczku/docker-machine-vultr#9]
It seems the only mounted root filesystem is of type "overlay", and sized arounds 350Mo.

Any idea why?

**Comment by janeczku** [comment]
Yes, VULTR changed something with their block storage preventing Rancher OS from automounting the disk. I will patch this later today.

**Comment by janeczku** [comment]
@docteurklein Please upgrade to the latest release and see if this solves the issue for you. Thanks!

**Comment by docteurklein** [comment]
@janeczku woah! you rock for such a fast answer :)

It totally works. Thanks a lot!
